name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: work/demo/go/src/github.com/nlimpid/demo
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.1" # The Go version to download (if necessary) and use.
      # This step prints an output (time) from the previous step's action.

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
        # env:
        #   GOPATH: /home/runner/work/nlimpid/go

      - name: Build
        run: sh build.sh
