name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/checkout@v1
      - uses: actions/setup-go@v1
      # This step prints an output (time) from the previous step's action.
      - name: Build
        run: sh build.sh