name: Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/demo/go
      GITHUB_TOKEN: ${{secrets.TOKEN}}
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.1"

      - name: checkout
        uses: actions/checkout@v1
        with:
          path: go/src/github.com/nlimpid/demo

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
          echo ${PWD}
      - name: Bench
        run: printenv

      - name: Docker Login
        run: |
          docker login docker.pkg.github.com --username nlimpid --password "${GITHUB_TOKEN}"

      - name: Build
        run: sh build.sh `git rev-parse HEAD`
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
